# actibelt dependencies image
FROM continuumio/miniconda3:latest

# Python packages from conda
RUN conda install -q -y -c conda-forge \
    make gxx_linux-64 r-e1071 numpy xarray pandas matplotlib tqdm six rpy2=2.9